# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements_ci.txt ]; then pip install -r requirements_ci.txt; fi
      continue-on-error: true
    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff --output-format=github .
      continue-on-error: true
    - name: set pythonpath
      run: |
        echo "PYTHONPATH=/home/runner/work/pisces/shared/:/home/runner/work/pisces/gui/" >> $GITHUB_ENV
    - name: Test with pytest
      run: |
        PYTHONPATH=./shared:./gui pytest
